language: python
python:
  - 2.7
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install astropy statsmodels scipy==1.2 supersmoother untrendy pygam
  - pip install scikit-learn==0.20  # later versions don't run on Python 2.7
script:
  - python setup.py install
  - python wotan/tests.py
