language: python
python:
  - 2.7
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install astropy statsmodels  scipy supersmoother untrendy pygam
  - pip install sklearn==0.20
script:
  - python setup.py install
  - python wotan/tests.py
